### ISSUE TITLE
Add all the test cases from node-semvar

### ISSUE THREAD

**Issue by andrew** [librariesio/semantic_range#1]
https://github.com/npm/node-semver/tree/master/test

- [x] big-numbers.js
- [x] clean.js
- [x] gtr.js
- [x] ltr.js
- [x] index.js
- [x] major-minor-patch.js - https://github.com/librariesio/semantic_range/pull/4

**Comment by krishandley** [comment]
Tests left to port from index.js

```test('\ndiff versions test', function(t) {```
https://github.com/npm/node-semver/blob/master/test/index.js#L431

```test('\ncomparators test', function(t) {```
https://github.com/npm/node-semver/blob/master/test/index.js#L547

```test('\ninvalid version numbers', function(t) {```
https://github.com/npm/node-semver/blob/master/test/index.js#L630

```test('\nstrict vs loose version numbers', function(t) {```
https://github.com/npm/node-semver/blob/master/test/index.js#L645

```test('\nstrict vs loose ranges', function(t) {```
https://github.com/npm/node-semver/blob/master/test/index.js#L670

```test('\nmax satisfying', function(t) {```
https://github.com/npm/node-semver/blob/master/test/index.js#L684

**Comment by krishandley** [comment]
@andrew https://github.com/npm/node-semver/blob/master/semver.js#L798 needed?

**Comment by andrew** [comment]
@krishandley I think we need it for https://github.com/npm/node-semver/blob/master/test/index.js#L622

**Comment by krishandley** [comment]
@andrew the comment said it was for legacy api reasons so just wanted to check :+1:

**Comment by andrew** [comment]
Yeah perhaps it makes more sense to add it as a function in `spec_helper.rb` instead

**Comment by krishandley** [comment]
@andrew I _think_ that's index.js done!

**Comment by andrew** [comment]
Great work!

**Comment by krishandley** [comment]
No problem :smile:
