### ISSUE TITLE
Can I compare two ranges with this library?

### ISSUE THREAD

**Issue by rtfpessoa** [librariesio/semantic_range#61]
## Question

Can I check if two `SemanticRange::Range` intersect with this library? What would be the method to call?

**Comment by andrew** [comment]
It doesn't support it directly but I think you can use `SemanticRange.to_comparators(range)` to break a range into its separate parts so they can be compared, for example:

    SemanticRange.to_comparators('~> 1.0.3') #=> ['>=1.0.3', '<1.1.0']

More examples in the specs: https://github.com/librariesio/semantic_range/blob/master/spec/semantic_range_spec.rb#L527-L606

**Comment by rtfpessoa** [comment]
I actually checked that, but how can I then compare for example '>1.0.3' with '>=1.0.3'? I cannot find any method that always takes the comparison operators into consideration.

**Comment by andrew** [comment]
What's the use case for comparing ranges? Are you looking for the intersection or which one is highest?

**Comment by rtfpessoa** [comment]
I am looking for the intersection. Example: I know that '<1.0.3' has a problem and I know that someone is using '>=1.0.3' and then I want to know if the problem is present in the usage.

**Comment by rtfpessoa** [comment]
If there is nothing maybe it can be done with a simple implementation of [Morgan's Law](https://en.wikipedia.org/wiki/De_Morgan%27s_laws).

Essentially just compare if `xmin <= ymax && ymin <= xmax`.

**Comment by andrew** [comment]
I think the only thing missing is the code to calculate what the min and max for a range is, and ranges can be a collection of ranges, for example `1.2.x || 2.x` -> `['>=1.2.0', '<1.3.0'], ['>=2.0.0', '<3.0.0']`

**Comment by rtfpessoa** [comment]
The main "problem" would just be unbounded ranges like '<3.0.0' or '>3.0.0'. 
For the first I think we can consider that 0.0.0 is the lowest minimum possible but for the second what would be the maximum?

**Comment by andrew** [comment]
2.99999.999999999 is the max if you ignore prereleases

**Comment by rtfpessoa** [comment]
When you say: `2.99999.999999999` is it `299999999999999.299999999999999.299999999999999` ? I looked into http://semver.org/ but I could not find the maximum. Maybe I need to read it more carefully.

**Comment by andrew** [comment]
As many 9s as you can type in theory, different package managers have different limits, usually on the total string length

**Comment by rtfpessoa** [comment]
After some testing I though that using min and max would be a real pain. Specially the min since I would need to have to find the max of the previous version ?!?

Before quitting I had an idea of basing the implementation on comparisons of comparators.

The initial code is here https://github.com/rtfpessoa/semantic_range/commit/dcf02d5b4fba409e59d98cd287c8c121eae53eb1

fyi, this was done after a long day so please read it with a big bowl of salt 😄 

As a baseline I already "tested" it with some local ideas:

```
SemanticRange.ranges_intersect('>1.3.0', '>1.4.0') #=> true
SemanticRange.ranges_intersect('<1.3.0', '>1.3.0') #=> false
SemanticRange.ranges_intersect('<1.3.0', '>=1.3.0') #=> false
SemanticRange.ranges_intersect('<=1.3.0', '>1.3.0') #=> false
SemanticRange.ranges_intersect('<=1.3.0', '>=1.3.0') #=> true
SemanticRange.ranges_intersect('<=1.3.0 || >=1.2.0 <=1.3.0', '>1.3.0') #=> false
SemanticRange.ranges_intersect('<=1.3.0 || >=1.2.0 <=1.3.1', '>1.3.0') #=> true
SemanticRange.ranges_intersect('<=1.3.0 >=1.2.0 <=1.3.1', '>1.3.0') #=> false
```

Let me know if this makes sense to you and if you find any problem. If you think this makes sense I will then make a proper PR with some real tests. Also suggestions for names are always welcome.

**Comment by andrew** [comment]
LGTM 👍

**Comment by rtfpessoa** [comment]
Just did some tests but for some reason in for example https://github.com/rtfpessoa/semantic_range/commit/6d50d8f654b40239de11ceae9b919dfdaae01aee#diff-9919d87eda5f711afd5077e400f8fabcR658 on the `Comparator` initializer the line `return comp if comp.loose == loose` fails saying that in `comp.loose` the loose is not a member. How is this possible?

**Comment by rtfpessoa** [comment]
I was able to "fix" it. When you have some time take a look to the PR.
