### ISSUE TITLE
How to represent all versions

### ISSUE THREAD

**Issue by rtfpessoa** [librariesio/semantic_range#68]
Is there a way to pass a range that represents all versions of a package?
I tough `*` would do it but it fails to parse. What should be the correct way?

**Comment by katzj** [comment]
You can do something like

```
irb(main):001:0> SemanticRange.satisfies('1.0.0', '>0.0.0')
=> true
```

**Comment by rtfpessoa** [comment]
@katzj thanks. Just one detail: wouldn't `>=0.0.0` be more correct?

**Comment by katzj** [comment]
Yes :)
