### ISSUE TITLE
Make it more ruby-ish

### ISSUE THREAD

**Issue by andrew** [librariesio/semantic_range#8]
There are lots of bits seconds that have been transposed straight from javascript and are fairly verbose, we can make them much nicer and more in line with standard ruby practises as @krishandley has started here: https://github.com/librariesio/semantic_range/pull/7

**Comment by krishandley** [comment]
Ruby :heart:

**Comment by andrew** [comment]
Feels a lot better now

**Comment by andrew** [comment]
Just released v1.0.0 https://rubygems.org/gems/semantic_range/versions/1.0.0 💃
